#!/usr/bin/env php
<?php
/*
 * This file is part of Nigatedev PHP framework package.
 * 
 * @author Abass Ben Cheik <abass@todaysdev.com>
 */
 
 require __DIR__. "/vendor/autoload.php";
 
 use Nigatedev\Console\Maker\Make;
 
 use Nigatedev\Console\Colors;
 
(new Make())->make($argv);

?>