#!/usr/bin/env php
<?php

/*
 * This file is part of the Niga framework package.
 *
 * (c) Abass Ben Cheik <abass@todaysdev.com>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (
    file_exists("./autoload.php")
    || file_exists("./vendor/autoload.php")
) {
    foreach ([
        "./autoload.php", "./vendor/autoload.php"
    ] as $loder) {
        if (file_exists($loder)) {
            require_once $loder;
            break;
        }
    }
} else {
    fwrite(
        STDERR,
        "\33[41mFATAL:\nNiga (CLI) can't find composer auto loader!"
            . "\33[0m\n\n\33[44mINFO:\nPlease install dependencies with 'composer install' to run this script"
            . PHP_EOL
    );

    exit(1);
}

(new Niga\Framework\Console\Console($argv));
