# Note: this configuration is depending on .env file
#
# MySQL default configuration
mysql:
    options:
        fetch_mode: "PDO::FETCH_OBJ"
  
# SQLite default configuration
sqlite:
#   When using sqlite as default driver you can change thi value to true only if-
#   you want to use sqlite in memory.
#   See https://www.php.net/manual/en/ref.pdo-sqlite.connection.php
    memory:
        in_memory: false
    
#   By default sqlite data is stored in %app.dir%/data/ directory
#   you can overwrite this, but public/* folder are not allowed 
    prefix_dir: "../data/"
    options:
        fetch_mode: "PDO::FETCH_OBJ"